# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: rails_audior_website_development
  username: rails_audior_website
  password: password
  encoding: utf8
  host: localhost

test:
  adapter: mysql2
  database: rails_audior_website_test
  username: rails_audior_website
  password: password
  encoding: utf8
  host: localhost